//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fridge_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smart_fridgeEntities : DbContext
    {
        public smart_fridgeEntities()
            : base("name=smart_fridgeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ingradient> ingradients { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<dish> dishes { get; set; }
        public virtual DbSet<category> categories { get; set; }
    }
}
