//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fridge_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingradient
    {
        public int id { get; set; }
        public int dish_id { get; set; }
        public int item_id { get; set; }
    }
}
